AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "spec/fixtures/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 6

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "ocak.gemspec"

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - "lib/ocak/templates/**/*"

Naming/PredicateMethod:
  Enabled: false
